### ISSUE TITLE
[Backend] Build Out List of Tags By Subcscriber

### ISSUE THREAD

**Issue by a-camarillo** [BobaTalks/bobabot#10]
## As a subscriber, I want to be able to view a list all of the tags I am currently subscribed to:

- [ ] Write query to return list of all tag names that contain a user ID
- [ ] Decide if this is it's own endpoint and how the data should be transferred from DB to Client. Currently only `/tags` endpoint.

**Comment by simku22** [comment]
query exists and is used for unsubscribing, can easily be run independently
