### ISSUE TITLE
[Backend] Create functionality for /tags/:id/subscribers route

### ISSUE THREAD

**Issue by a-camarillo** [BobaTalks/bobabot#2]
## Description
Since we decided on storing subscribers IDs as an array within the tag object this presents the issue of how we are going to handle updating the array when a user subscribes/unsubscribes. The most common HTTP method for updating a resource(in this case the /tags/:id object) is PUT, however this presents two problems:
1. PUT expects a new resource or a modified representation of the target resource meaning that when we are trying to update the array of subscriber IDs we are expected to send the entire tag object with an array that either includes or excludes the subscriber ID
2. Having a single method for both adding to/removing from the array seems conflicting and can possibly lead to unintended behavior

Instead of using PUT for `/tags/:id` we can extend the routing to include `/tags/:id/subscribers` and `/tags/:id/subscribers/:id` allowing us to use appropriate POST and DELETE methods for the updating of the subscriber IDs array
### Tracking Tickets

- [x] #3 
- [x] #4

**Comment by simku22** [comment]
completed; old ticket
