### ISSUE TITLE
 [Backend] Create GET functionality for /tags/:id/subscribers route

### ISSUE THREAD

**Issue by a-camarillo** [BobaTalks/bobabot#4]
## Description

- [ ]  Write database query to select the array of subscribers from the tag object with the given id
- [ ]  When a request is made to the endpoint, return either the array object containing all of the subscriber ids and a status code of 200 or an error for an unsuccessful/invalid request with a status code of 4xx

Example Request:
```
GET /tags/1/subscribers HTTP/1.1
Host: example.com
Content-Type: application/json
```
Example Response:
``` JSON
{
 [
    12345,
    67890,
    13579,
    24680
 ]
}
```

**Comment by jwu910** [comment]
Same question as the other issue, can we also outline the expected body for both the request and the response?
