### ISSUE TITLE
[Backend] Build Read(GET) for /tags/:id/subscribers/:id route

### ISSUE THREAD

**Issue by a-camarillo** [BobaTalks/bobabot#7]
- [ ]  Write database query to select the given subscriber id from the array of subscribers corresponding to the tag object with the given id
- [ ]  When a request is made to the endpoint, return either the array object containing all of subscriber ids and a status code of 200 or an error for an unsuccessful/invalid request with a status code of 4xx

Example Request:
```
GET /tags/1/subscribers/1 HTTP/1.1
Host: example.com
Content-Type: application/json
```

Example Response:
```json
{
  1
}
```

**Comment by simku22** [comment]
outdated
